[32m[0721 21:16:09 @logger.py:92][0m Argv: /usr/local/lib/python3.7/dist-packages/ipykernel_launcher.py -f /root/.local/share/jupyter/runtime/kernel-471362ae-9f3e-4d65-93ca-3ffeff54f511.json
[32m[0721 21:16:09 @fs.py:101][0m [5m[31mWRN[0m Env var $TENSORPACK_DATASET not set, using /root/tensorpack_data for datasets.
[32m[0721 21:16:09 @fs.py:104][0m Created the directory /root/tensorpack_data.
[32m[0721 21:16:09 @mnist.py:21][0m Downloading to /root/tensorpack_data/mnist_data/train-images-idx3-ubyte.gz...
[32m[0721 21:16:31 @fs.py:64][0m [4m[5m[31mERR[0m Failed to download http://yann.lecun.com/exdb/mnist/train-images-idx3-ubyte.gz
